# Exercise 6: Weather anomalies (10 points)

The aim of this exercise is to analyze historical weather data.
- In Problem 1 you read in a tricky data file and explore it's contents.
- In problem 2, you will convert and aggregate the data from daily temperatures in Fahrenheit, to monthly average temperatures in Celsius.
- In Problem 3, you will finally analyze weather anomalies by comparing monthly average temperatures to a long-term average.

### Tips for completing this exercise

- Use **exactly** the same variable names as in the instructions because your answers will be automatically graded, and the tests that grade your answers rely on following the same formatting or variable naming as in the instructions.
- **Please do not**:

    - **Change the file names**. Do all of your editing in the provided `Exercise-6-problems-1-3.ipynb` file (this file).
    - **Copy/paste cells in this notebook**. We use an automated grading system that will fail if there are copies of code cells.
    - **Change the existing cell types**. You can add cells, but changing the cell types for existing cells (from code to markdown, for example) will also cause the automated grader to fail.

## AI tool usage agreement

**Enter your name (and that of your partner) in the cell below** to confirm that you have followed the [course guidelines on the use of AI tools](https://geo-python-site.readthedocs.io/en/latest/course-info/ai-tools.html) and understand that misuse of AI tools is considered cheating.

YOUR ANSWER HERE

## Problem 1 - Reading in a tricky data file (2 points)

You first task for this exercise is to read in the data file [data/1091402.txt](data/1091402.txt) to a variable called `data`. Pay attention to the input data structure and no data values.

### Scores for this problem

**Your score on this problem will be based on following criteria:**

- Reading the data into a variable called `data` using pandas
    - Skipping the second row of the datafile that contains `----------` characters that don't belong to the data
    - Convert the no-data values (`-9999`) into `NaN` 
- Calculating basic statistics from the data
- Including comments that explain what most lines in the code do

### Part 1 (1 point)

You should start by loading the data file.

- Read the data file into variable the variable `data`
    - Skip the second row
    - Convert the no-data values (`-9999`) into `NaN`

In [2]:
import pandas as pd
data = pd.read_csv(
    "data/1091402.txt",
    sep=r"\s+", 
    skiprows=[1],
    na_values=-9999
)

In [3]:
# Check that the dataframe looks ok:
data.head(
    
)

,STATION,ELEVATION,LATITUDE,LONGITUDE,DATE,PRCP,TAVG,TMAX,TMIN
0,GHCND:FIE00142080,51,60.3269,24.9603,19520101,0.31,37.0,39.0,34.0
1,GHCND:FIE00142080,51,60.3269,24.9603,19520102,NaN,35.0,37.0,34.0
2,GHCND:FIE00142080,51,60.3269,24.9603,19520103,0.14,33.0,36.0,NaN
3,GHCND:FIE00142080,51,60.3269,24.9603,19520104,0.05,29.0,30.0,25.0
4,GHCND:FIE00142080,51,60.3269,24.9603,19520105,0.06,27.0,30.0,25.0

In [4]:
# Check the last rows of the data (there should be some NaN values)
data.tail()

,STATION,ELEVATION,LATITUDE,LONGITUDE,DATE,PRCP,TAVG,TMAX,TMIN
23711,GHCND:FIE00142080,51,60.3269,24.9603,20170930,NaN,47.0,49.0,44.0
23712,GHCND:FIE00142080,51,60.3269,24.9603,20171001,0.04,47.0,48.0,45.0
23713,GHCND:FIE00142080,51,60.3269,24.9603,20171002,NaN,47.0,49.0,46.0
23714,GHCND:FIE00142080,51,60.3269,24.9603,20171003,0.94,47.0,NaN,44.0
23715,GHCND:FIE00142080,51,60.3269,24.9603,20171004,0.51,52.0,56.0,NaN

In [5]:

print(data.columns)

Index(['STATION', 'ELEVATION', 'LATITUDE', 'LONGITUDE', 'DATE', 'PRCP', 'TAVG',
       'TMAX', 'TMIN'],
      dtype='str')

### Part 2 (1 point)

In this section, you will calculate some basic statistics of the input data.

- Calculate how many no-data (NaN) values there are in the `TAVG` column
    - Assign your answer to a variable called `tavg_nodata_count`

In [6]:
tavg_nodata_count = data["TAVG"].isna().sum()
# YOUR CODE HERE

In [7]:
# Print out the solution:
print(f'Number of no-data values in column "TAVG": {tavg_nodata_count}')

Number of no-data values in column "TAVG": 3308

- Calculate how many no-data (NaN) values there are for the `TMIN` column
    - Assign your answer into a variable called `tmin_nodata_count`

In [8]:
tmin_nodata_count = data["TMIN"].isna().sum()

In [9]:
# Print out the solution:
print(f'Number of no-data values in column "TMIN": {tmin_nodata_count}')

Number of no-data values in column "TMIN": 365

- Calculate the total number of days covered by this data file
    - Assign your answer into a variable called `day_count`

In [10]:
day_count = data["DATE"].count()

In [11]:
# Print out the solution:
print(f'Number of days: {day_count}')

Number of days: 23716

- Find the date of the oldest (first) observation
    - Assign your answer into a variable called `first_obs`

In [12]:
first_obs = data["DATE"].min()

In [13]:
# Print out the solution:
print(f'Date of the first observation: {first_obs}')

Date of the first observation: 19520101

- Find the date of the most recent (last) observation
    - Assign your answer into a variable called `last_obs`

In [14]:
last_obs = data["DATE"].max()
# YOUR CODE HER

In [15]:
# Print out the solution:
print(f'Date of the last observation: {last_obs}')

Date of the last observation: 20171004

- Find the average temperature for the whole data file (all observtions) from column `TAVG`
    - Assign your answer into a variable called `avg_temp`

In [16]:
avg_temp = data["TAVG"].mean()
avg_temp

np.float64(41.32408859270874)

In [17]:
# Print out the solution:
print(f'Average temperature (F) for the whole dataset: {round(avg_temp, 2)}')

Average temperature (F) for the whole dataset: 41.32

- Find the average `TMAX` temperature over the [Summer of '69](https://www.youtube.com/watch?v=9f06QZCVUHg) (months May, June, July, and August of the year 1969)
    - Assign your answer into a variable called `avg_temp_1969`

In [18]:
avg_temp_1969 = data.loc[(data["DATE"] >= 19690501) & 
                         (data["DATE"] < 19690901), "TMAX"].mean()

In [19]:
# This test print should print a number
print(f"Average temperature (F) for the Summer of '69: {round(avg_temp_1969, 2)}")

Average temperature (F) for the Summer of '69: 67.82

## Problem 2 - Calculating monthly average temperatures (3 points)

For this problem your goal is to calculate monthly average temperatures in degrees Celsius from the daily Fahrenheit values we have in the data file. You can continue working with the same DataFrame that you used in Problem 1.

### Scores for this problem

**Your score on this problem will be based on following criteria:**

- Calculating the monthly average temperatures in degrees Celsius for the each month in the dataset (i.e., for each month of each year)
    - You should store the monthly average temperatures in a new Pandas DataFrame called `monthly_data`
    - `monthly_data` should contain a new column called `temp_celsius` the monthly average temperatures in Celsius
    - Convert the `TAVG` values in Fahrenheit into Celsius and store the output in the `temp_celsius`
- Including comments that explain what most lines in the code do

**Hint**: *You can start by creating a new column with a label for each year and month, and then continue grouping the data based on this information.*

In [20]:
data["DATE"] = pd.to_datetime(data["DATE"], format="%Y%m%d")
YEAR_MONTH = data["DATE"].dt.to_period("M")
YEAR_MONTH.head()

#convert yyyymmdd to datetime format, then extract year and month

0    1952-01
1    1952-01
2    1952-01
3    1952-01
4    1952-01
Name: DATE, dtype: period[M]

In [21]:
monthly_data = data.groupby(YEAR_MONTH)["TAVG"].mean().reset_index()
monthly_data.head()

#Group by month, calculate mean for each month based on TAVG column

      DATE       TAVG
0  1952-01  29.478261
1  1952-02  24.800000
2  1952-03  13.807692
3  1952-04  39.607143
4  1952-05  44.666667

In [22]:
monthly_data["temp_celsius"] = (
    (monthly_data["TAVG"] - 32) * 5/9).round(0).astype("Int64")

monthly_data.head()

# Convert F to C, round to nearest integer, and convert to integer type. 
# Store in new column "temp_celsius"

      DATE       TAVG  temp_celsius
0  1952-01  29.478261            -1
1  1952-02  24.800000            -4
2  1952-03  13.807692           -10
3  1952-04  39.607143             4
4  1952-05  44.666667             7

In [23]:
monthly_data.drop("TAVG", axis=1, errors="ignore")
monthly_data.head()

# Drop the TAVG column, since we have the Celsius version now. 
# Use errors="ignore" to avoid an error if the column is already dropped.

      DATE       TAVG  temp_celsius
0  1952-01  29.478261            -1
1  1952-02  24.800000            -4
2  1952-03  13.807692           -10
3  1952-04  39.607143             4
4  1952-05  44.666667             7

In [24]:
# This test prints the length of variable monthly_data
print(len(monthly_data))

790

In [25]:
# This test prints the column names of monthly_data
print(monthly_data.columns.values)

<StringArray>
['DATE', 'TAVG', 'temp_celsius']
Length: 3, dtype: str

In [26]:
# This test prints the mean of temp_celsius
print(monthly_data['temp_celsius'].mean())

5.1114369501466275

In [27]:
# This test prints the median of temp_celsius
print(round(monthly_data['temp_celsius'].median(), 2))

5.0

## Problem 3 - Calculating temperature anomalies (5 points)

Our goal in this problem is to calculate monthly temperature anomalies in order to see how temperatures have changed over time, relative to an observation period between 1952-1980. You can continue working with the same data that you used in Problems 1 and 2.

**Your score on this problem will be based on following criteria:**

### Part 1

- Calculating ***the average (mean) temperature for each month (e.g., January, February, March, ...) over the period from 1952 up to and including 1980*** in a new DataFrame called `reference_temps`
    - You should end up with 12 values, 1 mean temperature for each month during the time period (see example table and figure below).
    - The columns in the new DataFrame should be `month` and `ref_temp`
    
Your `reference_temps` dataframe should have the following structure: 1 value for each month of the year (12 total) and the values represent and average in the observation period 1952-1980. The `ref_temp` temperatures should be in degrees Celsius.
   
| month    | ref_temp         |
|----------|------------------|
| 01       | -5.838761        |
| 02       | -7.064088        |
| 03       | -3.874213        |
| ...      | ...              |

### Part 2

- Calculating **a temperature anomaly for every month** in the `monthly_data` DataFrame using the corresponding monthly average temperature for each of the 12 months:
    - In order to achieve this you need to make **a table join** (see [hints for this week](https://geo-python-site.readthedocs.io/en/develop/lessons/L6/exercise-6.html#joining-data-from-one-dataframe-to-another)) between `monthly_data` and `ref_temps` based on the month.
    - The temperature anomaly is calculated as the difference between the temperature for a given month (`temp_celsius` column in `monthly_data`) and the corresponding monthly reference temperature (`ref_temp` column in`reference_temps`).
    - Store the result in a new column `"diff"` 
    
As the output of the table join and the calculation, you should have three new columns in the `monthly_data` DataFrame:

1. `diff`: The temperature anomaly, i.e. the difference between the temperature for a given month (e.g., February 1960) and the mean temperature during the reference period (e.g., the average of all Februaries between 1952 and 1980), 
2. `month`: The month for that row of observations
3. `ref_temp`: The monthly reference temperature

A summary of the relationships between the `monthly_data` and `reference_temps` DataFrames, as well as how the `diff` value should be calculated in the `monthly_data` DataFrame is presented in the figure below.

![Exercise 6 dataframes](img/exercise-6-dataframes.png)<br/>
*Figure 1. Relationships between the `monthly_data` and `reference_temps` DataFrames.*

You should finally report which month had the greatest weather anomaly during the observed time period.

Remember to include comments in your code.

In [28]:
# Check the monthly data:
monthly_data.head()

      DATE       TAVG  temp_celsius
0  1952-01  29.478261            -1
1  1952-02  24.800000            -4
2  1952-03  13.807692           -10
3  1952-04  39.607143             4
4  1952-05  44.666667             7

In [29]:
# Filter data to the reference period 1952-1980
reference_period = monthly_data[
    (monthly_data["DATE"].dt.year >= 1952) &
    (monthly_data["DATE"].dt.year <= 1980)
]
reference_period["month"] = reference_period["DATE"].dt.month
reference_period["year"] = reference_period["DATE"].dt.year
reference_period.sort_values(by=["month", "year"], inplace=True)

print(reference_period)

        DATE       TAVG  temp_celsius  month  year
0    1952-01  29.478261            -1      1  1952
12   1953-01  22.285714            -5      1  1953
24   1954-01  19.269231            -7      1  1954
36   1955-01  22.148148            -5      1  1955
48   1956-01  17.360000            -8      1  1956
..       ...        ...           ...    ...   ...
299  1976-12  24.225806            -4     12  1976
311  1977-12  25.161290            -4     12  1977
323  1978-12   9.032258           -13     12  1978
335  1979-12  25.129032            -4     12  1979
347  1980-12  26.645161            -3     12  1980

[348 rows x 5 columns]

In [30]:
reference_temps = reference_period.groupby(
    reference_period["DATE"].dt.month)["temp_celsius"].mean().reset_index()

#group by month, calculate mean for each month based on temp_celsius column

reference_temps.columns = ["month", "ref_temp"]
#rename columns

reference_temps

    month  ref_temp
0       1     -5.75
1       2      -7.1
2       3     -3.85
3       4      2.45
4       5       9.5
5       6     14.65
6       7      16.6
7       8     15.05
8       9      9.85
9      10      4.95
10     11      0.25
11     12     -4.15

In [31]:
monthly_data

        DATE       TAVG  temp_celsius
0    1952-01  29.478261            -1
1    1952-02  24.800000            -4
2    1952-03  13.807692           -10
3    1952-04  39.607143             4
4    1952-05  44.666667             7
..       ...        ...           ...
785  2017-06  56.300000            13
786  2017-07  60.290323            16
787  2017-08  60.290323            16
788  2017-09  52.333333            11
789  2017-10  48.250000             9

[790 rows x 3 columns]

In [32]:
monthly_data["month"] = monthly_data["DATE"].dt.month
#extract month from DATE 

monthly_data = monthly_data.merge(reference_temps, on="month", how="left")
# Merge the reference temp with the monthly data, using month as the key.

monthly_data

        DATE       TAVG  temp_celsius  month  ref_temp
0    1952-01  29.478261            -1      1     -5.75
1    1952-02  24.800000            -4      2      -7.1
2    1952-03  13.807692           -10      3     -3.85
3    1952-04  39.607143             4      4      2.45
4    1952-05  44.666667             7      5       9.5
..       ...        ...           ...    ...       ...
785  2017-06  56.300000            13      6     14.65
786  2017-07  60.290323            16      7      16.6
787  2017-08  60.290323            16      8     15.05
788  2017-09  52.333333            11      9      9.85
789  2017-10  48.250000             9     10      4.95

[790 rows x 5 columns]

In [33]:
monthly_data["diff"] = (
    monthly_data["temp_celsius"] - monthly_data["ref_temp"]
)
# Calculate the difference between temp_celsius and ref_temp

monthly_data

        DATE       TAVG  temp_celsius  month  ref_temp  diff
0    1952-01  29.478261            -1      1     -5.75  4.75
1    1952-02  24.800000            -4      2      -7.1   3.1
2    1952-03  13.807692           -10      3     -3.85 -6.15
3    1952-04  39.607143             4      4      2.45  1.55
4    1952-05  44.666667             7      5       9.5  -2.5
..       ...        ...           ...    ...       ...   ...
785  2017-06  56.300000            13      6     14.65 -1.65
786  2017-07  60.290323            16      7      16.6  -0.6
787  2017-08  60.290323            16      8     15.05  0.95
788  2017-09  52.333333            11      9      9.85  1.15
789  2017-10  48.250000             9     10      4.95  4.05

[790 rows x 6 columns]

In [42]:
monthly_data.drop(columns="month",inplace=True)
monthly_data

        DATE       TAVG  temp_celsius  ref_temp  diff
0    1952-01  29.478261            -1     -5.75  4.75
1    1952-02  24.800000            -4      -7.1   3.1
2    1952-03  13.807692           -10     -3.85 -6.15
3    1952-04  39.607143             4      2.45  1.55
4    1952-05  44.666667             7       9.5  -2.5
..       ...        ...           ...       ...   ...
785  2017-06  56.300000            13     14.65 -1.65
786  2017-07  60.290323            16      16.6  -0.6
787  2017-08  60.290323            16     15.05  0.95
788  2017-09  52.333333            11      9.85  1.15
789  2017-10  48.250000             9      4.95  4.05

[790 rows x 5 columns]

In [43]:
# Print out desriptive statistics for the relevant columns:
monthly_data[["temp_celsius", "ref_temp", "diff"]].describe()

       temp_celsius  ref_temp      diff
count         682.0     790.0     682.0
mean       5.111437  4.386835  0.722067
std        8.498728  8.279229  2.554158
min           -18.0      -7.1    -12.25
25%            -2.0     -3.85      -0.8
50%             5.0      4.95      0.85
75%            13.0     13.45      2.35
max            22.0      16.6       8.1

Remember also to calculate which month had the largest temperature anomaly during the observed time period in comparison with the reference data. Use the cell below to calculate and print out the answers. Note, you may want to consider the largest absolute value of the temperature anomaly, as well as the largest positive and negative anomalies.

In [44]:
max_row = monthly_data.loc[monthly_data["diff"].abs().idxmax()]
# Find the row with the largest absolute value of diff. 
max_row

DATE             1987-01
TAVG           -0.354839
temp_celsius         -18
ref_temp           -5.75
diff              -12.25
Name: 420, dtype: object

In [45]:
print(f"Greatest anomaly: {max_row['DATE']} with a diff of {max_row['diff']:.2f}°C")

Greatest anomaly: 1987-01 with a diff of -12.25°C

## Part 3 (*optional*) - **AI-LLM OK**

Using [ChatGPT](https://openai.com/chatgpt), calculate the reference temperatures and temperature anomalies as directed above.

- Your reference temperatures should be stored in a new DataFrame called `ai_reference_temps`
    - The columns in the new DataFrame should be `month` and `ai_ref_temp`
- Calculate **a temperature anomaly for every month** in the `monthly_data` DataFrame using the corresponding monthly average temperature for each of the 12 months:
    - You again need to make **a table join** (see [hints for this week](https://geo-python-site.readthedocs.io/en/develop/lessons/L6/exercise-6.html#joining-data-from-one-dataframe-to-another)) between `monthly_data` and `ai_ref_temps` based on the month.
    - The temperature anomaly is calculated as the difference between the temperature for a given month (`temp_celsius` column in `monthly_data`) and the corresponding monthly reference temperature (`ai_ref_temp` column in`reference_temps`).
    - Store the result in a new column `"ai_diff"` 

In order to do this, you should post both the prompt you provide to ChatGPT and the code it produces in the cells below. As your prompts may need to be refined to get your code working, please report each prompt so we can see how you arrived at your final version of the function.

### Prompt 1

Enter the text of the first prompt you used for this part of the exercise below.

YOUR ANSWER HERE

Enter the code generated by your first prompt below.

In [ ]:
# YOUR CODE HERE
raise NotImplementedError()

Looking at the function produced by ChatGPT do you see any problems compared to your solution in Part 1? Please comment below about this.

YOUR ANSWER HERE

Test out your code by running the tests below.

In [ ]:
# Check the monthly data:
monthly_data.head()

In [ ]:
# Print out desriptive statistics for the relevant columns:
monthly_data[["temp_celsius", "ai_ref_temp", "ai_diff"]].describe()

### Additional prompts

In the event your code does not pass all of the tests above, please enter the prompt(s) you used to refine the function in the cell below. If you used more than one prompt, you can format them as a Markdown list using the format demonstrated below:

```
1. First prompt
2. Second prompt
3. ...
```

If no additional prompts were needed, you can skip this.

YOUR ANSWER HERE

Enter the final version of your code produced by ChatGPT in the cell below. You can test the code by re-running the tests above after updating the code below.

In [ ]:
# YOUR CODE HERE
raise NotImplementedError()

Does your revised function now pass all of the tests?
- If yes, please comment below about your experience using ChatGPT and the benefits and drawbacks you see.
- If no, what kinds of problems do you see with the revised function produced by ChatGPT compared to your solution in Part 1? Please comment below about this.

YOUR ANSWER HERE

### Final comments

If you have any other comments about your experience using ChatGPT in this problem, please enter those below.

YOUR ANSWER HERE